//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.beer.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharsType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CharsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AlcoholContent" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         <element name="Transparency" type="{http://www.w3.org/2001/XMLSchema}float" maxOccurs="100" minOccurs="0"/>
 *         <element name="Filtered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="Calories" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         <element name="Packaging" type="{}PackagingType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharsType", propOrder = {
    "alcoholContent",
    "transparency",
    "filtered",
    "calories",
    "packaging"
})
public class CharsType {

    @XmlElement(name = "AlcoholContent")
    protected Float alcoholContent;
    @XmlElement(name = "Transparency", type = Float.class)
    protected List<Float> transparency;
    @XmlElement(name = "Filtered")
    protected boolean filtered;
    @XmlElement(name = "Calories")
    protected Float calories;
    @XmlElement(name = "Packaging", required = true)
    protected PackagingType packaging;

    /**
     * Gets the value of the alcoholContent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAlcoholContent() {
        return alcoholContent;
    }

    /**
     * Sets the value of the alcoholContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAlcoholContent(Float value) {
        this.alcoholContent = value;
    }

    /**
     * Gets the value of the transparency property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transparency property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTransparency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * </p>
     * 
     * 
     * @return
     *     The value of the transparency property.
     */
    public List<Float> getTransparency() {
        if (transparency == null) {
            transparency = new ArrayList<>();
        }
        return this.transparency;
    }

    /**
     * Gets the value of the filtered property.
     * 
     */
    public boolean isFiltered() {
        return filtered;
    }

    /**
     * Sets the value of the filtered property.
     * 
     */
    public void setFiltered(boolean value) {
        this.filtered = value;
    }

    /**
     * Gets the value of the calories property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCalories() {
        return calories;
    }

    /**
     * Sets the value of the calories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCalories(Float value) {
        this.calories = value;
    }

    /**
     * Gets the value of the packaging property.
     * 
     * @return
     *     possible object is
     *     {@link PackagingType }
     *     
     */
    public PackagingType getPackaging() {
        return packaging;
    }

    /**
     * Sets the value of the packaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagingType }
     *     
     */
    public void setPackaging(PackagingType value) {
        this.packaging = value;
    }

}
