//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.beer.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.beer.model package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.beer.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Beer }
     * 
     * @return
     *     the new instance of {@link Beer }
     */
    public Beer createBeer() {
        return new Beer();
    }

    /**
     * Create an instance of {@link BeerItemType }
     * 
     * @return
     *     the new instance of {@link BeerItemType }
     */
    public BeerItemType createBeerItemType() {
        return new BeerItemType();
    }

    /**
     * Create an instance of {@link PackagingType }
     * 
     * @return
     *     the new instance of {@link PackagingType }
     */
    public PackagingType createPackagingType() {
        return new PackagingType();
    }

    /**
     * Create an instance of {@link CharsType }
     * 
     * @return
     *     the new instance of {@link CharsType }
     */
    public CharsType createCharsType() {
        return new CharsType();
    }

    /**
     * Create an instance of {@link IngredientsType }
     * 
     * @return
     *     the new instance of {@link IngredientsType }
     */
    public IngredientsType createIngredientsType() {
        return new IngredientsType();
    }

}
